### ISSUE TITLE
-(1): Expected token type NEWLINE, but saw ID

### ISSUE THREAD

**Issue by chintapallipallavi** [uxmal/pytocs#39]
Hi ,

I am getting below issue please help me to resolve that.

![pytocsissue](https://user-images.githubusercontent.com/45621583/49565344-df100580-f94c-11e8-97db-be063222a454.JPG)

**Comment by uxmal** [comment]
You are not starting pytocs correctly in the visual studio debugger.  In the Solution Explorer, right click on the Cli project and select the "Properties" menu item.
In the project properties tab, select the "Debug " tab
In the debug tab, enter a correct command line in the "Command line" text box.

This issue is the same as #29
