### ISSUE TITLE
Pytocs should convert range to Enumerable.Range

### ISSUE THREAD

**Issue by SWATOPLUS** [uxmal/pytocs#47]
The following code:
```
def main():
 x = range(6)
 for n in x:
  print(n)
```

Will be translated to:
```
public static class Program {    
    public static object main() {
        var x = range(6);
        foreach (var n in x) {
            Console.WriteLine(n);
        }
    }
}
```
Expected result is:
```
using System.Linq;
public static class Program {    
    public static object main() {
        var x = Enumerable.Range(0,6);
        foreach (var n in x) {
            Console.WriteLine(n);
        }
    }
}
```

**Also should convert** `range(a, b);` to `Enumerable.Range(a,b-a)`

**Comment by uxmal** [comment]
Look at https://github.com/uxmal/pytocs/blob/master/src/Core/Translate/IntrinsicTranslator.cs, which is where you'll need to add a mapping from `"range"` to a function that will translate `range`.

**Comment by SWATOPLUS** [comment]
Python range description:
https://www.w3schools.com/python/ref_func_range.asp

As I read, range function can receive 1, 2 or 3 arguments. Let's look at each case.

If there is one argument, then it can be easy converted. Example:

```
range(count) -> Enumerable.Range(0, count)
```

If there are two arguments, then calculation of count required. Example:

```
range(start, stop) -> Enumerable.Range(start, stop - start)
```

If there are two arguments, then it will look so ugly. Example:

```
range(start, stop, step) -> Enumerable.Range(0, Convert.ToInt32(Math.Ceiling(Convert.ToDouble(stop - start) / step))).Select(x => start + x * step)
```    

Sample:

```
Print(range(10));
Print(range(2, 10));
Print(range(2, 10, 2));
Print(range(2, 10, 3));
Print(range(2, 10, 5));
Print(range(2, 10, 20));
```

Converter output:

```
Print(Enumerable.Range(0, 10));
Print(Enumerable.Range(2, 10 - 2));
Print(Enumerable.Range(0, Convert.ToInt32(Math.Ceiling(Convert.ToDouble(10 - 2) / 2))).Select(x => 2 + x * 2));
Print(Enumerable.Range(0, Convert.ToInt32(Math.Ceiling(Convert.ToDouble(10 - 2) / 3))).Select(x => 2 + x * 3));
Print(Enumerable.Range(0, Convert.ToInt32(Math.Ceiling(Convert.ToDouble(10 - 2) / 5))).Select(x => 2 + x * 5));
Print(Enumerable.Range(0, Convert.ToInt32(Math.Ceiling(Convert.ToDouble(10 - 2) / 20))).Select(x => 2 + x * 20));
```

C# interactive output:

```
RangeIterator { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 }
RangeIterator { 2, 3, 4, 5, 6, 7, 8, 9 }
Enumerable.WhereSelectEnumerableIterator<int, int> { 2, 4, 6, 8 }
Enumerable.WhereSelectEnumerableIterator<int, int> { 2, 5, 8 }
Enumerable.WhereSelectEnumerableIterator<int, int> { 2, 7 }
Enumerable.WhereSelectEnumerableIterator<int, int> { 2 }
```

**This code is compilable, but difficult to read. Is conversion to new static method (like Python.Range) more preferable?**

**Comment by SWATOPLUS** [comment]
Created PR #48

**Comment by uxmal** [comment]
I'd leave it as is for now -- it's not a common case. However, should there be complaints from users, it might be necessary to add a `range` method to the `Runtime` project for this case.

**Comment by ghost** [comment]
how do you run the converter?

**Comment by uxmal** [comment]
@michaelakool : hello and thanks for your interest in pytocs. As a side note, please open a new issue rather than adding a comment to an existing issue opened by another person: it minimizes the risk that your question may get missed.

The instructions for running pytocs are written in the README.md. Briefly, you have 2 choices. Either start the GUI client and use the provided controls to load a python file or directory, or use the command line client. In a directory that contains python code, type the following command:
```
pytocs mypythonfile.py
```
to translate a single file or 
```
pytocs -r .
```
to translate the current directory and any subdirectories.

**Comment by uxmal** [comment]
Closing as "implemented"

**Comment by ghost** [comment]
Is it possible you sent me a video or screenshots..
I will understand better

**Comment by uxmal** [comment]
@michaelakool : I've just fleshed out the [HOWTO.md](https://github.com/uxmal/pytocs/blob/master/doc/HOWTO.md) with clear instructions for how to download or compile and run `pytocs`. Please read that document carefully and follow the instructions.

Since I have no other channel to reach you I suggest, if you still have questions, please either a _new_ issue with your questions. Please don't add more comments to this closed issue.  Alternatively, you can use the gitter forum at https://gitter.im/uxmal/pytocs . I'm usually available Central European Time. I can speak any Scandinavian language, Spanish, French, or broken German, if you're more comfortable using any of those other languages.
