### ISSUE TITLE
Best-effort approach and bug report

### ISSUE THREAD

**Issue by MuleaneEve** [uxmal/pytocs#61]
First, thank you for working on this project, it is awesome!

I've been running it through some projects and I noticed that for most, the conversion can't complete. I just get an error message.
So, I hacked together some try/catch in the code in order to ignore parsing exceptions and attempt to output what was successfully converted.

Would you consider "hardening" pytocs like that?

You can try running it through a large Python project for testing...

.

Here is one example of the type of errors that would interrupt the whole process:

```
class TestClass:
    def TestFunction(self):
        return TestValue(
            {
                **something
            }
        )
```

The [Parser fails at line 2331](https://github.com/uxmal/pytocs/blob/c67dda9f62464c8224b5d4930529d887aced2025/src/Core/Syntax/Parser.cs#L2331) with k being null (which throws a NullRefEx).

**Comment by uxmal** [comment]
Thanks for the feedback! A basic assumption `pytocs` makes is that the input Python programs are syntactically correct. The parser is therefore not "hardened" for junk inputs, but will (metaphorically) throw up its hands as soon as it encounters a syntactic anomaly.  Of course, this presupposes that the `pytocs` Python parser is correctly implemented. As you've discovered, there still are cases where the parser fails, and when it fails, it fails hard.

I do "train" `pytocs` on large Python projects to discovered bugs like this, but naturally there is always the possibility that unparseable constructs exist in projects I'm unaware of. Now that you've reported this particular case, I can fix the problem. If you have any other Python projects that `pytocs` fails on I'd be happy to fix those errors too. Just send me the URL to the source trees.

As for "hardening" as you put it, I suppose I could change the `pytocs` parser to generate "error" tokens / terms rather than throwing exceptions. Certainly core methods in the parser, like `expr()` and `stmt()` could catch any exceptions, emit a warning, and return a stub identifier like `<parser-error>` or a stub statement like `# <parser-error>`.

**Comment by uxmal** [comment]
@MuleaneEve: I've implemented an exception handler in `stmt()`. Give it a whirl and see if it helps with stability.

**Comment by MuleaneEve** [comment]
Wow, that was fast :)

The exception handling is indeed better, but I was hoping that it would now allow a Folder Conversion to go through, even if some files are missing (with relevant error messages).

.

Regarding the specific example I gave, here is a similar one that doesn't work:

```
class TestClass:
    def TestFunction(self):
        return TestValue(
            {
                **something,
                **somethingElse
            }
        )
```

And here is another one:

```
class TestClass:
    def TestFunction(self):
        if (
           condition1
            and
            # Comment here => "not" is Unexpected
            not condition2
        ):
            return early
        return late
```

**Comment by MuleaneEve** [comment]
If you want to run pytocs through a large Python project, here is one (which has more unhandled scenarios):
https://github.com/ytdl-org/youtube-dl

**Comment by MuleaneEve** [comment]
By the way, my simplistic hack to make pytocs work on a whole folder even with errors is to make two changes:

1. Add a `catch() { ... }` to [AstCache.getAST()#L124](https://github.com/uxmal/pytocs/blob/86eff6aa3f0a26eddc67af554f5501e71c1172e4/src/Core/TypeInference/AstCache.cs#L124)
2. Add `if (module == null) continue;` in [ConversionUtils.ConvertFolderAsync()#L52](https://github.com/uxmal/pytocs/blob/86eff6aa3f0a26eddc67af554f5501e71c1172e4/src/Gui/ConversionUtils.cs#L52) for the Gui. And [same line for the Cli](https://github.com/uxmal/pytocs/blob/86eff6aa3f0a26eddc67af554f5501e71c1172e4/src/Cli/Program.cs#L73).

**Comment by uxmal** [comment]
OK, I will reactivate the issue and work on that project. If you find any more by all means let me know. I want pytocs to be able to parse as much Python as possible, but since the language spec keeps changing, it's an eternal job :P

**Comment by MuleaneEve** [comment]
Thank you. I didn't want to bother you :)

For your quest of handling "all" of Python, there are loads of projects on GitHub:
https://github.com/topics/python?l=python

You can download a bunch, unzip them all in the same directory, and have fun converting them.

Edit: By the way, that's how the team at Microsoft that wrote [Roslyn](https://github.com/dotnet/roslyn) tested their new compiler.

**Comment by uxmal** [comment]
I've made a few commits that should address the issues you mentioned above. After the fixes, `pytocs` manages to parse https://github.com/ytdl-org/youtube-dl without crashing. I'll close the issue again, and look at some other large Python projects in my spare time. Thanks for reporting this!

**Comment by MuleaneEve** [comment]
Thanks again!
